### ISSUE TITLE
Array Index error in Websocket messages

### ISSUE THREAD

**Issue by bspeice** [kaitai-io/kaitai_struct_formats#143]
Right now, the websocket format uses `_root.dataframes[0]` to figure out the payload type. The issue is that `_root.dataframes[0]` doesn't exist for the first dataframe, so when the constructor gets called to read (which is eagerly evaluated), there's an array index error.

Given that messages are guaranteed to be at least 1 dataframe long, should the format be updated to have an initial frame, and then all frames following?

EDIT: That doesn't actually work either, because now there's a NPE accessing `_root.first_frame` because the constructor runs too quickly.

**Comment by GreyCat** [comment]
PNG format actually follows similar idea: special handling of header frames.

**Comment by bspeice** [comment]
Alright, got the parser cleaned up and can confirm that the Java version is doing the correct thing. I'll open a pull request shortly.
