### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [kaitai-io/kaitai_struct_formats#2]
I'm trying to understand doom_wad.ksy, but I'm having trouble because the language is almost completely undocumented except for the GIF example. Doom_wad.ksy uses several features of the KSY language that aren't used in the GIF example and aren't documented anywhere.

The commit log mentions a change that was made "per spec". Where is this spec? I couldn't find it on kaitai.io or in any of the repositories.

**Comment by GreyCat** [comment]
Have you seen [language reference in project's wiki](https://github.com/kaitai-io/kaitai_struct/wiki/Language-reference)?

I believe that all the stuff used in `doom_wad.ksy` should be documented there.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I didn't know there was a wiki. Thanks!

**Comment by GreyCat** [comment]
Actually, you've brought up quite a good idea: we should add a more visible link to the docs. Probably lots of people couldn't find them. Thanks!
