### ISSUE TITLE
jpeg.ksy doesn't have all segments declared

### ISSUE THREAD

**Issue by s4chin** [kaitai-io/kaitai_struct_formats#22]
So I'm using this version which solves a lot of problems - https://github.com/koczkatamas/kaitai_struct_formats/tree/fix/compile-workarounds.
As all the `appn` segments are not declared there, it gives an error when it encounters one or more undeclared segments. Should I add them and submit a PR?

**Comment by GreyCat** [comment]
Sure, please go ahead :)

Unfortunately, JPEG standard is pretty long and even then there are quite a few different subtypes exist under the same "JPEG file" moniker - so it will probably still needs some work.
