### ISSUE TITLE
ethernet_frame.ksy with q-tag

### ISSUE THREAD

**Issue by H4rryK4ne** [kaitai-io/kaitai_struct_formats#245]
Hi,

I need to implement the q-tag into the ethernet_frame.ksy (see https://en.wikipedia.org/wiki/IEEE_802.1Q). 

Currently I just add a q-tag with a fixed size (of 4 bytes) before the ether_type id, since all my data has this tag, but this is obviously not the proper way to do it. 
Unfortunatly I have no Idea how to check the ether_type, and if it is 0x8100 than to add 4 bytes to the q-tag and than apply the ether_type again. 

Best regards,
Martin

**Comment by GreyCat** [comment]
It's generally a matter of simple `if` + some extra types to support that additional structure.

I went ahead and made a change: https://github.com/kaitai-io/kaitai_struct_formats/pull/246 — please review this PR and see if it works for you?

**Comment by H4rryK4ne** [comment]
Hi @GreyCat 
I also found a solution on friday, although, I am not happy with the naming. May be you can take a look into this file: [ethernet_frame.ksy](https://github.com/kaitai-io/kaitai_struct_formats/files/3857494/ethernet_frame.ksy.txt)
I haven't took much effort into the TCI, as you did, since I'm not interested in the content.

**Comment by GreyCat** [comment]
Your solution does not seem to match the frame format declared in 802.1Q (that specifies exactly one TPID/TCI pair, your one seems to accept any number of them), and also it makes it hard for end-user to access `ether_type` (one needs use something like `tag.last.tpid`).

**Comment by H4rryK4ne** [comment]
You are completely right. I misinterpreted the double tag defined IEEE 802.1ad. I'm rather new to this stuff.

**Comment by GreyCat** [comment]
To be fair, the implementation I've proposed does not cover double tags as per 802.1ad too, likely the overall approach can be extended to cover that in future. Thanks for the review!
