### ISSUE TITLE
Replace duplicate `doc-ref` keys with list in magicavoxel_vox.ksy

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_formats#281]
It's invalid to have duplicate keys in YAML:

https://github.com/kaitai-io/kaitai_struct_formats/blob/2c318560d46a64a3338e531ff1540716dab9798c/media/magicavoxel_vox.ksy#L8-L9

We already have support for lists in `doc-ref` (https://github.com/kaitai-io/kaitai_struct/issues/269), so this should be replaced with an array of two strings. Like this:

https://github.com/kaitai-io/kaitai_struct_formats/blob/2c318560d46a64a3338e531ff1540716dab9798c/image/bmp.ksy#L206-L208

**Comment by GreyCat** [comment]
It also needs `ks-version: 0.9`, and that will automatically break rendering on formats.kaitai.io ;)

I need to finish https://github.com/kaitai-io/kaitai_struct_formats/pull/257 to complete 0.9 support

**Comment by generalmimon** [comment]
> I need to finish #257 to complete 0.9 support

Can I help you with that or are you working on it?
