### ISSUE TITLE
Replace duplicate `doc-ref` keys with list in wav.ksy

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_formats#282]
See https://github.com/kaitai-io/kaitai_struct_formats/issues/281.

https://github.com/kaitai-io/kaitai_struct_formats/blob/2c318560d46a64a3338e531ff1540716dab9798c/media/wav.ksy#L18-L19

**Comment by Mingun** [comment]
This issue already fixed.
