### ISSUE TITLE
Python parsers does not implement from_file

### ISSUE THREAD

**Issue by lirlocker** [kaitai-io/kaitai_struct_formats#306]
_Edit: I just noticed that it's not only the LVM2 parser which doesn't implement that method but all Python parsers._

Although the usage (example: https://formats.kaitai.io/lvm2/python.html) states that you could "parse a local file and get structure in memory", the "from_file" function is not implemented.

Thanks.

**Comment by dgelessus** [comment]
If you mean that the KS-generated parser code doesn't contain a `from_file` method definition: that's normal. `from_file` is [defined in the `kaitaistruct.KaitaiStruct` class](
https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/4b974204a0d4d811ca5340d1b80acbfcface65b1/kaitaistruct.py#L31-L39). All KS-generated struct classes extend `KaitaiStruct` and inherit `from_file` and a few other methods. You should be able to call `Lvm2.from_file(...)` at runtime.
