### ISSUE TITLE
Some TTF files can't parsed

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct_formats#351]
Parsing of [NDCAlpha1.zip](https://github.com/kaitai-io/kaitai_struct_formats/files/5406558/NDCAlpha1.zip) with ttf.ksy failed in https://ide.kaitai.io/devel/ with error:

> Parse error: undefined
> Call stack: undefined EOFError: requested 1 bytes, but only 0 bytes available

The error is gone if comment usage of `post` type:
https://github.com/kaitai-io/kaitai_struct_formats/blob/53a38bd530bcb41d4eded7983cda61238046844b/font/ttf.ksy#L71-L73

**Comment by armijnhemel** [comment]
This is because the current parser tries to read beyond the end of stream in the post table. https://github.com/kaitai-io/kaitai_struct_formats/pull/579 fixes this.
