### ISSUE TITLE
TCP header options is part of body field in tcp_segment.ksy

### ISSUE THREAD

**Issue by vrpcse** [kaitai-io/kaitai_struct_formats#353]
As per current tcp_segment.ksy, options (from TCP header) is part of body field.
So if we only concern about the body, we need to explicitly exclude options and we do not know about the options length.
So is it fine to have a update in ksy as below?

```ksy
seq:
  - id: src_port
    type: u2
  - id: dst_port
    type: u2
  - id: seq_num
    type: u4
  - id: ack_num
    type: u4
  - id: data_offset
    type: b4
  - id: reserved
    type: b6
  - id: flags
    type: b6
  - id: window_size
    type: u2
  - id: checksum
    type: u2
  - id: urgent_pointer
    type: u2
  - id: options
    size: (data_offset * 4) - 20
    if: ((data_offset * 4) - 20) != 0
  - id: body
    size-eos: true
```

**Comment by GreyCat** [comment]
Thanks @vrpcse! I've added your suggestion to tcp_segment.ksy, this allows to work around some option issues with parsing some of TCP payloads. Ideally, we'd want to have more proper parsing, but even skipping like you've suggested makes sense and allows to progress.
