### ISSUE TITLE
Add a license for jpeg.ksy and exif.ksy

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_formats#382]
Files [`jpeg.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/7d2894cba0363eb9d74edeb434eafbc0ecc7c7ac/image/jpeg.ksy) and [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/7d2894cba0363eb9d74edeb434eafbc0ecc7c7ac/image/exif.ksy) (the latter was created by merging former specs [`exif_be.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_be.ksy) and [`exif_le.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_le.ksy)) have no `/meta/license` key, which means that they are under exclusive copyright. All contributors hold the copyright to the lines of code that they contributed and nobody else shall legally use them (see https://choosealicense.com/no-permission/).

Therefore, it is desirable to choose some license for them. I'll put a list of all contributors to the files [`jpeg.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/jpeg.ksy) and [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/exif.ksy) (+ [`exif_be.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_be.ksy) and [`exif_le.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_le.ksy)) below according to the Git history. If you're mentioned, **please comment if you are comfortable with [`CC0-1.0`](https://spdx.org/licenses/CC0-1.0.html) for both these files**. If not, suggest an alternative (e.g. [`MIT`](https://spdx.org/licenses/MIT.html)).

 - [`jpeg.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/jpeg.ksy)
   - [x] @GreyCat ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/jpeg.ksy?author=GreyCat))
   - [x] @koczkatamas ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/jpeg.ksy?author=koczkatamas))
   - [x] @s4chin ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/jpeg.ksy?author=s4chin))
 - [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/exif.ksy) (+ [`exif_be.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_be.ksy) and [`exif_le.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_le.ksy))
   - [x] @GreyCat (commits on [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/exif.ksy?author=GreyCat))
   - [x] @koczkatamas (commits on [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/exif.ksy?author=koczkatamas))
   - [x] @s4chin (commits on [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/exif.ksy?author=s4chin), [`exif_be.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_be.ksy?author=s4chin) and [`exif_le.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_le.ksy?author=s4chin))
   - [x] @lusceu (commits on [`exif_be.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_be.ksy?author=lusceu) and [`exif_le.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/cde1b06de6fc639df99cd62fca9cd07634c64d2a/image/exif_le.ksy?author=lusceu))
   - [x] @generalmimon (commits on [`exif.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/master/image/exif.ksy?author=generalmimon))

**Comment by GreyCat** [comment]
I'm fully ok with CC0-1.0 on both.

**Comment by lusceu** [comment]
Also fine with CC0-1.0.

**Comment by generalmimon** [comment]
I'm also ok with CC0-1.0.

What about @koczkatamas and @s4chin?

**Comment by koczkatamas** [comment]
I am also okay with CC0-1.0

**Comment by generalmimon** [comment]
@s4chin, do you agree with releasing all changes that you made in commit https://github.com/kaitai-io/kaitai_struct_formats/commit/24e2d00048b8084ceec30a187a79cb87a79a48ba under the [CC0-1.0](https://spdx.org/licenses/CC0-1.0.html) license?

**Comment by s4chin** [comment]
Yes I agree. Sorry for the late reply, missed the previous emails.

**Comment by generalmimon** [comment]
Thank you all for your cooperation!
