### ISSUE TITLE
Add a license for executable/mach_o.ksy

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_formats#411]
The spec [`executable/mach_o.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy) has no `/meta/license` key, which means that it is under exclusive copyright. All contributors hold the copyright to the lines of code that they contributed and nobody else shall legally use them (see https://choosealicense.com/no-permission/).

Therefore, it is desirable to choose a license for it. I'll put a list of contributors here according to [Git history](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy). If you're mentioned, **please comment whether you are OK with releasing the [`mach_o.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy) spec under the [`MIT` license](https://spdx.org/licenses/MIT.html)**. _(If not, suggest an alternative from [this list](https://spdx.org/licenses/).)_

* [`mach_o.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy)

  - [x] @GreyCat ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy?author=GreyCat))
  - [x] @koczkatamas ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy?author=koczkatamas))
  - [x] @FilippoBiga ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy?author=FilippoBiga))
  - [x] @pachoo ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy?author=pachoo))
  - [x] @generalmimon ([commits](https://github.com/kaitai-io/kaitai_struct_formats/commits/1eae5145325bb992e20dae838dd68d04814dda46/executable/mach_o.ksy?author=generalmimon))

**Comment by FilippoBiga** [comment]
Please confirm this as my confirmation that a I’m ok with releasing the spec under the MIT license. Thanks!

**Comment by koczkatamas** [comment]
I am okay with the MIT license.

**Comment by generalmimon** [comment]
I agree with the `MIT` license.

What about @GreyCat and @pachoo?

**Comment by pachoo** [comment]
I'm happy with the MIT license.

**Comment by GreyCat** [comment]
Sure, herby I agree with MIT as well.

**Comment by generalmimon** [comment]
> Sure, hereby I agree with MIT as well.

Thanks! Can you also add the license for that [`font/pcf_font.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/font/pcf_font.ksy)?

**Comment by GreyCat** [comment]
Done: https://github.com/kaitai-io/kaitai_struct_formats/commit/3c308f0f7060c52cf89fc8f9c25691fff72c85d1

**Comment by generalmimon** [comment]
Thank you all for your cooperation!
