### ISSUE TITLE
suggestion: rename asus_trx.ksy to broadcom_trx.ksy

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#429]
The TRX format is not specific to ASUS devices, but instead it is the standard format of firmware files on Broadcom based devices:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/mtd/partitions/brcm,trx.txt

A more complete specification of the two TRX formats can be found here:

http://web.archive.org/web/20190127154419/https://openwrt.org/docs/techref/header

**Comment by KOLANICH** [comment]
Thanks for the info!
