### ISSUE TITLE
Proposal: reserved and unassigned RTP payload types

### ISSUE THREAD

**Issue by john-aws** [kaitai-io/kaitai_struct_formats#498]
Currently, the RTP payload schemas indicate enumerated values like:

```
19: reserved3
20: unassigned1
21: unassigned2
```

Wondering if it would be more valuable as follows:

```
19: reserved19
20: unassigned20
21: unassigned21
```

This would not only indicate the reserved/unassigned nature of the payload type but also its specific type number.

And thank you for this project; very useful.

**Comment by generalmimon** [comment]
> Wondering if it would be more valuable as follows:
> 
> ```
> 19: reserved19
> 20: unassigned20
> 21: unassigned21
> ```
> 
> This would not only indicate the reserved/unassigned nature of the payload type but also its specific type number.

Thanks for pointing this out. Yes, this makes sense, it is the consensus mentioned in https://github.com/kaitai-io/kaitai_struct_formats/pull/448#discussion_r593899987. Any chance you can prepare a pull request fixing that?

> And thank you for this project; very useful.

Glad to hear that :)

**Comment by john-aws** [comment]
Hi, yes I'll take a look at this, probably next week. Thanks.
