### ISSUE TITLE
proposal: add signed version of vlq_base128

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#510]
There are a few formats (such as Dalvik bytecode) that have fields that are in so called "signed leb128" notation. Currently only the unsigned version of leb128 is supported in Kaitai.

**Comment by generalmimon** [comment]
Resolved by https://github.com/kaitai-io/kaitai_struct_formats/commit/ae405502323328de07496dc099c96da1944a170c. I forgot to reference this issue with the keyword ["Closes ..."](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) from the commit message so I need to close it manually ;)
