### ISSUE TITLE
ELF: 'global' is a reserved keyword in Python

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#511]
The latest ELF .ksy doesn't work when the parser is generated for python, because of:

```ksy
  symbol_binding:
    0:
      id: local
      doc: not visible outside the object file containing their definition
    1:
      id: global
      doc: visible to all object files being combined
```

The generated code looks like this:

```python
    class SymbolBinding(Enum):
        local = 0
        global = 1
        weak = 2
        os10 = 10
        os11 = 11
        os12 = 12
        proc13 = 13
        proc14 = 14
        proc15 = 15

```

global is unfortunately a reserved keyword in Python:

https://docs.python.org/3/reference/lexical_analysis.html#keywords

meaning that the generated code barfs.

Perhaps it should be renamed to `stb_global` or `global_symbol`.

**Comment by generalmimon** [comment]
Instance of https://github.com/kaitai-io/kaitai_struct/issues/90
