### ISSUE TITLE
vlq_base128_le incorrectrly compiled in C#

### ISSUE THREAD

**Issue by mikhail-khalizev** [kaitai-io/kaitai_struct_formats#559]
Hi.

Source file: `common/vlq_base128_le.ksy` 

Look in screenshot below, it is source file compiled for C#.
Since by default csharp uses Int32 type, shifts by '35', '42', '49' computes incorrectly.

![image](https://user-images.githubusercontent.com/18654696/141166692-ce125222-7c0f-408f-a35c-e15b357392d4.png)

Possible workaround to cast values to `u8` in `vlq_base128_le.ksy`:
```ksy
  value:
    value: >-
      (groups[0].value.as<u8>
      + (len >= 2 ? (groups[1].value.as<u8> << 7) : 0)
      + (len >= 3 ? (groups[2].value.as<u8> << 14) : 0)
      + (len >= 4 ? (groups[3].value.as<u8> << 21) : 0)
      + (len >= 5 ? (groups[4].value.as<u8> << 28) : 0)
      + (len >= 6 ? (groups[5].value.as<u8> << 35) : 0)
      + (len >= 7 ? (groups[6].value.as<u8> << 42) : 0)
      + (len >= 8 ? (groups[7].value.as<u8> << 49) : 0)).as<u8>
```

**Comment by yav** [comment]
I just run into this issue as well, but when experimenting with the C++ backend.   I can't seem to find any information on the type inference algorithm for Kaitai structs, so I am not sure if this is a bug in the compiler or the spec, but fixing it as suggested above seems reasonable to me.

The current status, where the spec looks simple, but when you try to parse some large numbers you get the wrong result is pretty unfortunate.

**Comment by generalmimon** [comment]
@yav:

> I can't seem to find any information on the type inference algorithm for Kaitai structs

See https://github.com/kaitai-io/kaitai_struct/issues/257#issuecomment-330971868.

> but fixing it as suggested above seems reasonable to me.
> 
> The current status, where the spec looks simple, but when you try to parse some large numbers you get the wrong result is pretty unfortunate.

I agree.
